// <auto-generated />
using System;
using Kursverwaltung.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kursverwaltung.Migrations
{
    [DbContext(typeof(KursverwaltungContext))]
    partial class KursverwaltungContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kursverwaltung.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschreibung");

                    b.Property<int>("Kursnummer");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Kurs");
                });

            modelBuilder.Entity("Kursverwaltung.Models.Teilnehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teilnehmer");
                });

            modelBuilder.Entity("Kursverwaltung.Models.TeilnehmerTermin", b =>
                {
                    b.Property<int>("TeilnehmerId");

                    b.Property<int>("TerminId");

                    b.HasKey("TeilnehmerId", "TerminId");

                    b.HasIndex("TerminId");

                    b.ToTable("TeilnehmerTermin");
                });

            modelBuilder.Entity("Kursverwaltung.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KursId");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.ToTable("Termin");
                });

            modelBuilder.Entity("Kursverwaltung.Models.TeilnehmerTermin", b =>
                {
                    b.HasOne("Kursverwaltung.Models.Teilnehmer", "Teilnehmer")
                        .WithMany("TeilnehmerTermine")
                        .HasForeignKey("TeilnehmerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kursverwaltung.Models.Termin", "Termin")
                        .WithMany("TeilnehmerTermine")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kursverwaltung.Models.Termin", b =>
                {
                    b.HasOne("Kursverwaltung.Models.Kurs", "Kurs")
                        .WithMany("Termine")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
